Extension { #name : 'Object' }

{ #category : '*VM-Plugins-Primitives' }
Object >> sqInt [

	<primitive: 'primitive_sqInt' module: 'UtilsPlugin'>
	self primitiveFail
]

{ #category : '*VM-Plugins-Primitives' }
Object >> sqObjectInt [

	<primitive: 'primitive_sqObjectInt' module: 'UtilsPlugin'>
	self primitiveFail
]

{ #category : '*VM-Plugins-Primitives' }
Object >> timsortSortKey [

	^ self yourself
]
